repos:
  - repo: local
    hooks:
      - id: pytest-changed-worlds
        name: pytest
        entry: pytest -rA --tb=short
        args: [worlds/rac3]
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        stages: [pre-commit]