"""This module contains position constants for checkpoints"""
from enum import IntFlag

from worlds.rac3.constants.items import RAC3ITEM


class WEAPONMOD(IntFlag):
    """Bitflags for weapon mods"""
    SHOCK = 0b00000010
    ACID = 0b00001000
    LOCK_ON = 0b00100000

    ALL = SHOCK | ACID | LOCK_ON


# weapon mods mapped to their corresponding weapons and the bit set for their unlock
WEAPON_MOD_TO_WEAPON: dict[str, tuple[str, int]] = {
    RAC3ITEM.MOD_SHOCK_SHOCK_BLASTER: (RAC3ITEM.SHOCK_BLASTER, WEAPONMOD.SHOCK),
    RAC3ITEM.MOD_ACID_SHOCK_BLASTER: (RAC3ITEM.SHOCK_BLASTER, WEAPONMOD.ACID),
    RAC3ITEM.MOD_LOCKON_SHOCK_BLASTER: (RAC3ITEM.SHOCK_BLASTER, WEAPONMOD.LOCK_ON),
    RAC3ITEM.MOD_SHOCK_NITRO_LAUNCHER: (RAC3ITEM.NITRO_LAUNCHER, WEAPONMOD.SHOCK),
    RAC3ITEM.MOD_ACID_NITRO_LAUNCHER: (RAC3ITEM.NITRO_LAUNCHER, WEAPONMOD.ACID),
    RAC3ITEM.MOD_LOCKON_NITRO_LAUNCHER: (RAC3ITEM.NITRO_LAUNCHER, WEAPONMOD.LOCK_ON),
    RAC3ITEM.MOD_SHOCK_N60_STORM: (RAC3ITEM.N60_STORM, WEAPONMOD.SHOCK),
    RAC3ITEM.MOD_ACID_N60_STORM: (RAC3ITEM.N60_STORM, WEAPONMOD.ACID),
    RAC3ITEM.MOD_LOCKON_N60_STORM: (RAC3ITEM.N60_STORM, WEAPONMOD.LOCK_ON),
    RAC3ITEM.MOD_SHOCK_PLASMA_WHIP: (RAC3ITEM.PLASMA_WHIP, WEAPONMOD.SHOCK),
    RAC3ITEM.MOD_ACID_PLASMA_WHIP: (RAC3ITEM.PLASMA_WHIP, WEAPONMOD.ACID),
    RAC3ITEM.MOD_LOCKON_PLASMA_WHIP: (RAC3ITEM.PLASMA_WHIP, WEAPONMOD.LOCK_ON),
    RAC3ITEM.MOD_SHOCK_INFECTOR: (RAC3ITEM.INFECTOR, WEAPONMOD.SHOCK),
    RAC3ITEM.MOD_ACID_INFECTOR: (RAC3ITEM.INFECTOR, WEAPONMOD.ACID),
    RAC3ITEM.MOD_LOCKON_INFECTOR: (RAC3ITEM.INFECTOR, WEAPONMOD.LOCK_ON),
    RAC3ITEM.MOD_SHOCK_SUCK_CANNON: (RAC3ITEM.SUCK_CANNON, WEAPONMOD.SHOCK),
    RAC3ITEM.MOD_ACID_SUCK_CANNON: (RAC3ITEM.SUCK_CANNON, WEAPONMOD.ACID),
    RAC3ITEM.MOD_LOCKON_SUCK_CANNON: (RAC3ITEM.SUCK_CANNON, WEAPONMOD.LOCK_ON),
    RAC3ITEM.MOD_SHOCK_SPITTING_HYDRA: (RAC3ITEM.SPITTING_HYDRA, WEAPONMOD.SHOCK),
    RAC3ITEM.MOD_ACID_SPITTING_HYDRA: (RAC3ITEM.SPITTING_HYDRA, WEAPONMOD.ACID),
    RAC3ITEM.MOD_LOCKON_SPITTING_HYDRA: (RAC3ITEM.SPITTING_HYDRA, WEAPONMOD.LOCK_ON),
    RAC3ITEM.MOD_SHOCK_AGENTS_OF_DOOM: (RAC3ITEM.AGENTS_OF_DOOM, WEAPONMOD.SHOCK),
    RAC3ITEM.MOD_ACID_AGENTS_OF_DOOM: (RAC3ITEM.AGENTS_OF_DOOM, WEAPONMOD.ACID),
    RAC3ITEM.MOD_LOCKON_AGENTS_OF_DOOM: (RAC3ITEM.AGENTS_OF_DOOM, WEAPONMOD.LOCK_ON),
    RAC3ITEM.MOD_SHOCK_FLUX_RIFLE: (RAC3ITEM.FLUX_RIFLE, WEAPONMOD.SHOCK),
    RAC3ITEM.MOD_ACID_FLUX_RIFLE: (RAC3ITEM.FLUX_RIFLE, WEAPONMOD.ACID),
    RAC3ITEM.MOD_LOCKON_FLUX_RIFLE: (RAC3ITEM.FLUX_RIFLE, WEAPONMOD.LOCK_ON),
    RAC3ITEM.MOD_SHOCK_ANNIHILATOR: (RAC3ITEM.ANNIHILATOR, WEAPONMOD.SHOCK),
    RAC3ITEM.MOD_ACID_ANNIHILATOR: (RAC3ITEM.ANNIHILATOR, WEAPONMOD.ACID),
    RAC3ITEM.MOD_LOCKON_ANNIHILATOR: (RAC3ITEM.ANNIHILATOR, WEAPONMOD.LOCK_ON),
    RAC3ITEM.MOD_SHOCK_HOLO_SHIELD: (RAC3ITEM.HOLO_SHIELD, WEAPONMOD.SHOCK),
    RAC3ITEM.MOD_ACID_HOLO_SHIELD: (RAC3ITEM.HOLO_SHIELD, WEAPONMOD.ACID),
    RAC3ITEM.MOD_LOCKON_HOLO_SHIELD: (RAC3ITEM.HOLO_SHIELD, WEAPONMOD.LOCK_ON),
    RAC3ITEM.MOD_SHOCK_DISC_BLADE: (RAC3ITEM.DISC_BLADE, WEAPONMOD.SHOCK),
    RAC3ITEM.MOD_ACID_DISC_BLADE: (RAC3ITEM.DISC_BLADE, WEAPONMOD.ACID),
    RAC3ITEM.MOD_LOCKON_DISC_BLADE: (RAC3ITEM.DISC_BLADE, WEAPONMOD.LOCK_ON),
    RAC3ITEM.MOD_SHOCK_RIFT_INDUCER: (RAC3ITEM.RIFT_INDUCER, WEAPONMOD.SHOCK),
    RAC3ITEM.MOD_ACID_RIFT_INDUCER: (RAC3ITEM.RIFT_INDUCER, WEAPONMOD.ACID),
    RAC3ITEM.MOD_LOCKON_RIFT_INDUCER: (RAC3ITEM.RIFT_INDUCER, WEAPONMOD.LOCK_ON),
    RAC3ITEM.MOD_SHOCK_QWACK_O_RAY: (RAC3ITEM.QWACK_O_RAY, WEAPONMOD.SHOCK),
    RAC3ITEM.MOD_ACID_QWACK_O_RAY: (RAC3ITEM.QWACK_O_RAY, WEAPONMOD.ACID),
    RAC3ITEM.MOD_LOCKON_QWACK_O_RAY: (RAC3ITEM.QWACK_O_RAY, WEAPONMOD.LOCK_ON),
    RAC3ITEM.MOD_SHOCK_RY3N0: (RAC3ITEM.RY3N0, WEAPONMOD.SHOCK),
    RAC3ITEM.MOD_ACID_RY3N0: (RAC3ITEM.RY3N0, WEAPONMOD.ACID),
    RAC3ITEM.MOD_LOCKON_RY3N0: (RAC3ITEM.RY3N0, WEAPONMOD.LOCK_ON),
    RAC3ITEM.MOD_SHOCK_MINI_TURRET: (RAC3ITEM.MINI_TURRET, WEAPONMOD.SHOCK),
    RAC3ITEM.MOD_ACID_MINI_TURRET: (RAC3ITEM.MINI_TURRET, WEAPONMOD.ACID),
    RAC3ITEM.MOD_LOCKON_MINI_TURRET: (RAC3ITEM.MINI_TURRET, WEAPONMOD.LOCK_ON),
    RAC3ITEM.MOD_SHOCK_LAVA_GUN: (RAC3ITEM.LAVA_GUN, WEAPONMOD.SHOCK),
    RAC3ITEM.MOD_ACID_LAVA_GUN: (RAC3ITEM.LAVA_GUN, WEAPONMOD.ACID),
    RAC3ITEM.MOD_LOCKON_LAVA_GUN: (RAC3ITEM.LAVA_GUN, WEAPONMOD.LOCK_ON),
    RAC3ITEM.MOD_SHOCK_SHIELD_CHARGER: (RAC3ITEM.SHIELD_CHARGER, WEAPONMOD.SHOCK),
    RAC3ITEM.MOD_ACID_SHIELD_CHARGER: (RAC3ITEM.SHIELD_CHARGER, WEAPONMOD.ACID),
    RAC3ITEM.MOD_LOCKON_SHIELD_CHARGER: (RAC3ITEM.SHIELD_CHARGER, WEAPONMOD.LOCK_ON),
    RAC3ITEM.MOD_SHOCK_BOUNCER: (RAC3ITEM.BOUNCER, WEAPONMOD.SHOCK),
    RAC3ITEM.MOD_ACID_BOUNCER: (RAC3ITEM.BOUNCER, WEAPONMOD.ACID),
    RAC3ITEM.MOD_LOCKON_BOUNCER: (RAC3ITEM.BOUNCER, WEAPONMOD.LOCK_ON),
    RAC3ITEM.MOD_SHOCK_PLASMA_COIL: (RAC3ITEM.PLASMA_COIL, WEAPONMOD.SHOCK),
    RAC3ITEM.MOD_ACID_PLASMA_COIL: (RAC3ITEM.PLASMA_COIL, WEAPONMOD.ACID),
    RAC3ITEM.MOD_LOCKON_PLASMA_COIL: (RAC3ITEM.PLASMA_COIL, WEAPONMOD.LOCK_ON),
}
WEAPON_MODPACK_TO_WEAPON: dict[str, str] = {
    RAC3ITEM.MODPACK_SHOCK_BLASTER: RAC3ITEM.SHOCK_BLASTER,
    RAC3ITEM.MODPACK_NITRO_LAUNCHER: RAC3ITEM.NITRO_LAUNCHER,
    RAC3ITEM.MODPACK_N60_STORM: RAC3ITEM.N60_STORM,
    RAC3ITEM.MODPACK_PLASMA_WHIP: RAC3ITEM.PLASMA_WHIP,
    RAC3ITEM.MODPACK_INFECTOR: RAC3ITEM.INFECTOR,
    RAC3ITEM.MODPACK_SUCK_CANNON: RAC3ITEM.SUCK_CANNON,
    RAC3ITEM.MODPACK_SPITTING_HYDRA: RAC3ITEM.SPITTING_HYDRA,
    RAC3ITEM.MODPACK_AGENTS_OF_DOOM: RAC3ITEM.AGENTS_OF_DOOM,
    RAC3ITEM.MODPACK_FLUX_RIFLE: RAC3ITEM.FLUX_RIFLE,
    RAC3ITEM.MODPACK_ANNIHILATOR: RAC3ITEM.ANNIHILATOR,
    RAC3ITEM.MODPACK_HOLO_SHIELD: RAC3ITEM.HOLO_SHIELD,
    RAC3ITEM.MODPACK_DISC_BLADE: RAC3ITEM.DISC_BLADE,
    RAC3ITEM.MODPACK_RIFT_INDUCER: RAC3ITEM.RIFT_INDUCER,
    RAC3ITEM.MODPACK_QWACK_O_RAY: RAC3ITEM.QWACK_O_RAY,
    RAC3ITEM.MODPACK_RY3N0: RAC3ITEM.RY3N0,
    RAC3ITEM.MODPACK_MINI_TURRET: RAC3ITEM.MINI_TURRET,
    RAC3ITEM.MODPACK_LAVA_GUN: RAC3ITEM.LAVA_GUN,
    RAC3ITEM.MODPACK_SHIELD_CHARGER: RAC3ITEM.SHIELD_CHARGER,
    RAC3ITEM.MODPACK_BOUNCER: RAC3ITEM.BOUNCER,
    RAC3ITEM.MODPACK_PLASMA_COIL: RAC3ITEM.PLASMA_COIL,
}
WEAPON_TO_WEAPON_MODPACK: dict[str, str] = {v: k for k, v in WEAPON_MODPACK_TO_WEAPON.items()}
