"""This module contains string constants for each object location"""


class RAC3OBJECT:
    """String constants for objects"""
    #DRACO
    DRACO_SCOUTBOT_01 = "Obani Draco: Scoutbot 01: Landing Point"
    DRACO_SCOUTBOT_02 = "Obani Draco: Scoutbot 02: Landing Point"
    DRACO_SCOUTBOT_03 = "Obani Draco: Scoutbot 03: First Tunnel"
    DRACO_SCOUTBOT_04 = "Obani Draco: Scoutbot 04: First Tunnel"
    DRACO_SCOUTBOT_05 = "Obani Draco: Scoutbot 05: First Tunnel"
    DRACO_SCOUTBOT_06 = "Obani Draco: Scoutbot 06: First Tunnel"
    DRACO_SCOUTBOT_07 = "Obani Draco: Scoutbot 07: First Tunnel"
    DRACO_SCOUTBOT_08 = "Obani Draco: Scoutbot 08: First Tunnel"
    DRACO_SCOUTBOT_09 = "Obani Draco: Scoutbot 09: Tunnel after strafe path"
    DRACO_SCOUTBOT_10 = "Obani Draco: Scoutbot 10: Tunnel after strafe path"
    DRACO_SCOUTBOT_11 = "Obani Draco: Scoutbot 11: Tunnel after strafe path"
    DRACO_SCOUTBOT_12 = "Obani Draco: Scoutbot 12: Tunnel after strafe path"
    DRACO_SCOUTBOT_13 = "Obani Draco: Scoutbot 13: Tunnel after strafe path"
    DRACO_SCOUTBOT_14 = "Obani Draco: Scoutbot 14: Spiral"
    DRACO_SCOUTBOT_15 = "Obani Draco: Scoutbot 15: Spiral"
    DRACO_SCOUTBOT_16 = "Obani Draco: Scoutbot 16: Spiral"
    DRACO_SCOUTBOT_17 = "Obani Draco: Scoutbot 17: Spiral"
    DRACO_SCOUTBOT_18 = "Obani Draco: Scoutbot 18: Spiral"
    DRACO_SCOUTBOT_19 = "Obani Draco: Scoutbot 19: Mirrorball Room"
    DRACO_SCOUTBOT_20 = "Obani Draco: Scoutbot 20: Mirrorball Room"
    DRACO_SCOUTBOT_21 = "Obani Draco: Scoutbot 21: Mirrorball Room"
    DRACO_SCOUTBOT_22 = "Obani Draco: Scoutbot 22: Mirrorball Room"
    DRACO_SCOUTBOT_23 = "Obani Draco: Scoutbot 23: Mirrorball Room"
    DRACO_SCOUTBOT_24 = "Obani Draco: Scoutbot 24: Mirrorball Room"
    DRACO_SCOUTBOT_25 = "Obani Draco: Scoutbot 25: Mirrorball Room"
    DRACO_SCOUTBOT_26 = "Obani Draco: Scoutbot 26: Tunnel after Mirrorball Room"
    DRACO_SCOUTBOT_27 = "Obani Draco: Scoutbot 27: Tunnel after Mirrorball Room"
    DRACO_SCOUTBOT_28 = "Obani Draco: Scoutbot 28: Tunnel after Mirrorball Room"
    DRACO_SCOUTBOT_29 = "Obani Draco: Scoutbot 29: Tunnel after Mirrorball Room"
    DRACO_SCOUTBOT_30 = "Obani Draco: Scoutbot 30: Tunnel after Mirrorball Room"
    DRACO_SCOUTBOT_31 = "Obani Draco: Scoutbot 31: Tunnel after Mirrorball Room"
    DRACO_SCOUTBOT_32 = "Obani Draco: Scoutbot 32: Tunnel after Mirrorball Room"
    DRACO_SCOUTBOT_33 = "Obani Draco: Scoutbot 33: Tunnel after Mirrorball Room"
    DRACO_SCOUTBOT_34 = "Obani Draco: Scoutbot 34: Tunnel after Mirrorball Room"
    DRACO_SCOUTBOT_35 = "Obani Draco: Scoutbot 35: Tunnel after Mirrorball Room"
    DRACO_SCOUTBOT_36 = "Obani Draco: Scoutbot 36: Tunnel after Mirrorball Room"
    DRACO_SCOUTBOT_37 = "Obani Draco: Scoutbot 37: Tunnel after Mirrorball Room"
    #MIGHT BE MISSABLE AFTER THIS POINT
    DRACO_NANOTECH_CRATE = "Obani Draco: Nanotech Crate: Courtney Fight"
    DRACO_AMMO_CRATE_01 = "Obani Draco: Ammo Crate 01: Courtney Fight"
    DRACO_AMMO_CRATE_02 = "Obani Draco: Ammo Crate 02: Courtney Fight"
    DRACO_AMMO_CRATE_03 = "Obani Draco: Ammo Crate 03: Courtney Fight"
    DRACO_DANCER_01 = "Obani Draco: Dancer 01: Courtney Fight"
    DRACO_DANCER_02 = "Obani Draco: Dancer 02: Courtney Fight"
    DRACO_DANCER_03 = "Obani Draco: Dancer 03: Courtney Fight"
    DRACO_DANCER_04 = "Obani Draco: Dancer 04: Courtney Fight"
    DRACO_DANCER_05 = "Obani Draco: Dancer 05: Courtney Fight"
    DRACO_DANCER_06 = "Obani Draco: Dancer 06: Courtney Fight"
    DRACO_DANCER_07 = "Obani Draco: Dancer 07: Courtney Fight"
    DRACO_DANCER_08 = "Obani Draco: Dancer 08: Courtney Fight"
    DRACO_DANCER_09 = "Obani Draco: Dancer 09: Courtney Fight"
    DRACO_COURTNEY_01 = "Obani Draco: Courtney Gears: Courtney Fight"
